language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
branches:
  except:
    - appveyor

sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b599153d-599b-4475-ba1b-c35ebdaa1ad6